PaintingSHop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.add_view, name='add_view'),
    path('add_onchange/<int:item_id>/', views.add_view, name='onchange_add_view'),
    path('remove/<int:item_id>/', views.cart_remove, name='cart_remove')

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('checkout/', views.create_order_view, name='checkout'),
]

store/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static


app_name = 'store'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('<int:id>/<slug:slug>/shop-detail', views.item_detail_view, name='shop-detail'),
    path('<int:id>/<slug:slug>/gallery-detail', views.gallery_detail_view, name='gallery-detail'),
    path('categories/<slug:slug>/', views.categories_view, name='category_view'),
    path('about/', views.about_view, name='about_view'),
    path('contact-us/', views.contact_view, name='contact_view'),
    path('gallery/', views.gallery_view, name='gallery_view'),
    path('shop/', views.shop_view, name='shop_view'),
    path('pricing/', views.pricing_view, name='pricing'),
    path('thank-you/', views.tahnk_you_view, name='thank-you'),
    path('shop/<slug:slug>/', views.shop_category_view, name='shop_category_view')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.urls import reverse
from decimal import Decimal


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    picture = models.ImageField(blank=False, default='index.jpeg')

    def get_absolute_url(self):
        return reverse('store:category_view', args=[self.slug])

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class ActiveItemManager(models.Manager):
    def get_queryset(self):
        return super(ActiveItemManager, self).get_queryset().filter(active=True)


class ShopItem(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, db_index=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    date_expires = models.DateTimeField()

    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()
    description = models.TextField()
    active = models.BooleanField(default=True)

    picture = models.ImageField(blank=False, default='index.jpeg')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='ShopItems')

    objects = models.Manager()
    active_items = ActiveItemManager()

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:shop-detail', args=[self.id, self.slug])


class GalleryItem(models.Model):
    name = models.CharField(max_length=20)
    active = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    primary_picture = models.ImageField(blank=False, default='index.jpeg')
    slug = models.SlugField(max_length=200, db_index=True)
    date_added = models.DateTimeField(auto_now_add=True)

    description = models.CharField(max_length=1000, default='**Awesome** picture, and *model*.')

    objects = models.Manager()
    active_items = ActiveItemManager()

    class Meta:
        ordering = ('-date_added',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:gallery-detail', args=[self.id, self.slug])


class GalleryPicture(models.Model):
    gallery_item = models.ForeignKey(GalleryItem, on_delete=models.CASCADE)
    picture = models.ImageField(blank=False, default='index.jpeg')
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.gallery_item.name + ' #' + str(self.id)

class DeliveryOption(models.Model):
    picture = models.ImageField(blank=False, default='index.jpeg')
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.name

    def get_price(self):
        return Decimal(self.price)


    class Meta:
        ordering = ('price',)

cart/forms.py
from django import forms
from store.models import DeliveryOption
from cart.cart import Cart

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,5)]

class AddCartForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update_quantity = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class UpdateOnChangeForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, widget=forms.Select(attrs={'onchange': 'this.form.submit();'}))
    update_quantity = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class UpdateOnChangeDelivery(forms.Form):
    class Meta:
        model = Cart
        fields = ['delivery']

store/forms.py
from django import forms

class SendEmailForm (forms.Form):
    name = forms.CharField(max_length=50, min_length=4,
                           widget=forms.TextInput(attrs={'placeholder': "Your Name", 'class': "form-control"}))
    email = forms.EmailField(widget=forms.TextInput(
        attrs={'class': "form-control", 'name': "email", 'placeholder': "Your Email", 'data-error': "Please enter Your Email"}))
    subject = forms.CharField(max_length=50, min_length=3, widget=forms.TextInput
        (attrs={'class': "form-control", 'name': "subject", 'placeholder': "Subject of the message", 'data-error': "Please enter Your name"}))
    message = forms.CharField(max_length=2000, widget=forms.TextInput
        (attrs={'class': "form-control", 'id': "message", 'placeholder': "Your message:", 'data-error': "Write Your message", 'rows': "4"}))

    send_copy = forms.BooleanField(label="Would You like a copy of a message?   ", initial=False, required=False)


class SearchForm(forms.Form):
    slug = forms.CharField(max_length=20, min_length=2, label=False, initial='Search here...')

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import AddCartForm, UpdateOnChangeForm
from store.models import ShopItem
from .cart import Cart
from django.views.decorators.http import require_POST

@require_POST
def generic_add_view(request, item_id, form):
    item = get_object_or_404(ShopItem.active_items.filter(id=item_id))
    cart = Cart(request)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(item, quantity=cd['quantity'], update_quantity=cd['update_quantity'])

    return redirect('cart:cart_detail')


def add_view(request, item_id):
    form = AddCartForm(request.POST)
    return generic_add_view(request, item_id, form)


def add_onchange_view(request, item_id):
    form = UpdateOnChangeForm(request.POST)
    return generic_add_view(request, item_id, form)


def cart_remove(request, item_id):
    item = get_object_or_404(ShopItem.objects.filter(id=item_id))
    cart = Cart(request)
    cart.remove(item)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)

    for item in cart:
        item['update_quantity_form'] = UpdateOnChangeForm(initial={'quantity': item['quantity'],
                                                    'update_quantity': True})
    return render(request, 'store/cart.html', {'cart': cart})

store/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect
from .models import ShopItem, Category, GalleryItem, DeliveryOption
from cart.forms import AddCartForm
from .forms import SendEmailForm, SearchForm
from django.core.mail import send_mail


def index_view(request):
    shop_items = ShopItem.active_items.all()
    gallery_items = GalleryItem.active_items.all()[:3]

    return render(request, 'store/index.html', {'shop_items': shop_items,'gallery_items': gallery_items})


def item_detail_view(request, slug, id):
    item = get_object_or_404(ShopItem, active=True, slug=slug, id=id)
    cart_form = AddCartForm()
    return render(request, 'store/shop-detail.html', {'item': item, 'cart_form': cart_form})


def gallery_detail_view(request, slug, id):
    gallery_item = get_object_or_404(GalleryItem, active=True, slug=slug, id=id)

    return render(request, 'store/gallery-detail.html', {'gallery_item': gallery_item})


def categories_view(request, slug=None):
    spec_category = get_object_or_404(Category, slug=slug)
    shop_items = ShopItem.active_items.filter(category=spec_category)

    return render(request, 'store/category.html', {'shop_items': shop_items, 'spec_category': spec_category})


def contact_view(request):
    form = SendEmailForm()

    if request.method == 'POST':
        form = SendEmailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = cd['subject']
            message = cd['message']
            author = cd['email']

            send_mail(subject, message, author, ['happyskullpainting@gmail.com'], fail_silently=True)
            if cd['send_copy']:
                send_mail('Copy: {}'.format(subject), 'Copy of message sent in PaintingStore: \n\n{}'.format(message),
                          author, [author], fail_silently=True)
            return redirect('/thank-you/')

    else:
        form = SendEmailForm()

    return render(request, 'store/contact-us.html', {'form': form})


def about_view(request):
    return render(request, 'store/about.html')


def pricing_view(reuest):
    delivery_options = DeliveryOption.objects.all()
    return render(reuest, 'store/pricing.html', {'delivery_options': delivery_options})


def gallery_view(request):
    gallery_items = GalleryItem.active_items.all()

    return render(request, 'store/gallery.html', {'gallery_items': gallery_items})


def shop_search_form(request):
    form = SearchForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data['slug']
        shop_items = ShopItem.active_items.filter(name__icontains=cd)
    else:
        form = SearchForm()
        shop_items = None
    return render(request, 'store/shop.html', {'shop_items': shop_items, 'form': form})


def shop_view(request, category=None):
    if request.method == 'POST':
        return shop_search_form(request)

    else:
        shop_items = ShopItem.active_items.all()
        form = SearchForm()
        return render(request, 'store/shop.html', {'shop_items': shop_items, 'form': form})


def shop_category_view(request, slug=None):

    if request.method == 'POST':
        return shop_search_form(request)

    else:
        shop_items = ShopItem.active_items.filter(category__slug__icontains=slug)
        form = SearchForm()
        return render(request, 'store/shop.html', {'shop_items': shop_items, 'form': form})


def tahnk_you_view(request):
    return render(request, 'store/thank-you.html')

store/templates/store/about.html
{% extends "store/base.html" %}
{% load static %}

{% block categories %}
    <!-- Start About Page  -->
    <div class="about-box-main">
        <div class="container">
            <div class="row">
				<div class="col-lg-6">
                    <div class="banner-frame"> <img class="img-fluid" src="{% static 'store/images/theme_done.jpg' %}" alt="" />
                    </div>
                </div>
                <div class="col-lg-6">
                    <h2 class="noo-sh-title-top">Smiley <span>Skull</span> Painting</h2>
                    <p>I have started my adventure with the hobby over 10 years ago - as a teenager.</p>

                        <p>After trying some comisison painting for friends at college, I decided to create a full fledged miniature painting service. During this time, I had an opportunity to work with various models from different manufacturers, and it has always been a blast!</p>

                    <p>I always feel, that being able to make a living out of a hobby is an amazing oportunity. I hope that you will enjoy my work as much as I do!</p>

                <p>If you have any questions about my projects, or just feel like chatting about the hobby, feel free to contact me :) Don't forget to check my portfolio on the website!</p>


                </div>
            </div>


            </div>
        </div>
    </div>
    <!-- End About Page -->

{% endblock %}

store/templates/store/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<!-- Basic -->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Site Metas -->
    <title>SMP.com</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'store/images/only_skull.png' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'store/images/apple-touch-icon.png' %}">

    <!-- Bootstrap CSS -->
    <link href="{% static 'store/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap core CSS -->

    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'store/css/style.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'store/css/responsive.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'store/css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Start Main Top -->
    <div class="main-top">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="right-phone-box">
                        <p><i class="fas fa-headset"></i>  Call US :- <a href="#"> +48 692 164 589</a></p>

                    </div>
                    <div class="right-phone-box">
                        <p>  </p>
                    </div>
                    <div class="right-phone-box">
                        <p><i class="fas fa-location-arrow"></i>  Email US :- <a href="#">happyskullpainting@gmail.com</a></p>
                    </div>
                </div>

                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
					<div class="text-slid-box">
                        <div id="offer-box" class="carouselTicker">
                            <ul class="offer-box">
                                {% for category in categories %}
                                <li>
                                    <b>{{ category.name }}</b>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Main Top -->

    <!-- Start Main Top -->
    <header class="main-header">
        <!-- Start Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-default bootsnav">
            <div class="container">
                <!-- Start Header Navigation -->
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                    <a class="navbar-brand" href="/"><img src="{% static 'store/images/logo_smiley_skull_with_bg.png' %}"  class="logo" alt="" width="160" height="104"></a>
                </div>
                <!-- End Header Navigation -->

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-menu">
                    <ul class="nav navbar-nav ml-auto" data-in="fadeInDown" data-out="fadeOutUp">
                        <li class="nav-item active"><a class="nav-link" href="/">Main page</a></li>
                        <li class="nav-item"><a class="nav-link" href="/about/">About us</a></li>
                        <li class="dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">SHOP &darr;</a>
                            <ul class="dropdown-menu">
								<li><a href="/shop/">SHOP</a></li>
                                <li><a href="/cart/">Cart</a></li>
                                <li><a href="/pricing/">Pricing</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="/gallery/">Gallery</a></li>
                        <li class="dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Categories &darr;</a>
                            <ul class="dropdown-menu">
                                {% for category in categories %}
                                <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="/contact-us/">Contact</a></li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->

                <!-- Start Atribute Navigation -->
                <div class="attr-nav">
                    <ul>

                        <li>
							<a href="{% url 'cart:cart_detail' %}">
								<i class="fa fa-shopping-bag"></i>
								<span class="badge">
                                    {{ cart|length }}
                                </span>
                                <p> Cart</p>
							</a>
						</li>
                    </ul>
                </div>
                <!-- End Atribute Navigation -->
            </div>
            <!-- Start Side Menu -->
            {% block slide_menu %}
            {% endblock %}
            <!-- End Side Menu -->
        </nav>
        <!-- End Navigation -->
    </header>
    <!-- End Main Top -->


    <!-- Start Slider -->

    <!-- End Slider -->

    <!-- Start Categories  -->
    {% block categories %}

    {% endblock %}
    <!-- End Categories -->
	


    <!-- Start Products  -->
    {% block products %}

    {% endblock %}
    <!-- End Products  -->

    <!-- Start Blog  -->
    {% block blog %}
    {% endblock %}
    <!-- End Blog  -->





    <!-- Start Footer  -->
    <footer>
        <div class="footer-main">
            <div class="container">
				<div class="row">

				</div>
				<hr>
                <div class="row">

                    <div class="col-lg-6 col-md-12 col-sm-12">
                        <div class="footer-link-contact">
                            <h4>Info</h4>
                            <ul>
                                <li> <p><i class="fas"></i><a href="/about/">About</a></p></li>
                                <li> <p><i class="fas"></i><a href="/pricing/">Pricing and delivery</a></p></li>
                                <li> <p><i class="fas"></i><a href="/orders/checkout/">Checkout</a></p></li>
                                <li> <p><i class="fas"></i><a href="/gallery/">Gallery/Portfolio</a></p></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12">
                        <div class="footer-link-contact">
                            <h4>Contact us if you have ANY questions:</h4>
                            <ul>
                                <li>
                                    <p><i class="fas fa-map-marker-alt"></i>Address: Emil Klonowski <br>Zielona Gora, Poland<br> 65-128 </p>
                                </li>
                                <li>
                                    <p><i class="fas fa-phone-square"></i>Phone: <a href="tel:+1-888705770">+48 692 164 589</a></p>
                                </li>
                                <li>
                                    <p><i class="fas fa-envelope"></i>Email: <a href="mailto:happyskullpainting@gmail.com">happyskullpainting@gmail.com</a></p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer  -->

    <!-- Start copyright  -->
    <div class="footer-copyright">
        <p class="footer-company">All Rights Reserved. &copy; 2020 Design By : Emil Klonowski
    </div>
    <!-- End copyright  -->

    <a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a>

    <!-- ALL JS FILES -->
    <script src="{% static 'store/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'store/js/popper.min.js' %}"></script>
    <script src="{% static 'store/js/bootstrap.min.js' %}"></script>
    <!-- ALL PLUGINS -->
    <script src="{% static 'store/js/jquery.superslides.min.js' %}"></script>
    <script src="{% static 'store/js/bootstrap-select.js' %}"></script>
    <script src="{% static 'store/js/inewsticker.js' %}"></script>
    <script src="{% static 'store/js/bootsnav.js' %}"></script>
    <script src="{% static 'store/js/images-loded.min.js' %}"></script>
    <script src="{% static 'store/js/isotope.min.js' %}"></script>
    <script src="{% static 'store/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'store/js/baguetteBox.min.js' %}"></script>
    <script src="{% static 'store/js/form-validator.min.js' %}"></script>
    <script src="{% static 'store/js/contact-form-script.js' %}"></script>
    <script src="{% static 'store/js/custom.js' %}"></script>
</body>

</html>

store/templates/store/cart.html
{% extends "store/base.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<!-- Basic -->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Site Metas -->
    <title>ThewayShop - Ecommerce Bootstrap 4 HTML Template</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'store/images/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'store/images/apple-touch-icon.png' %}">

    <!-- Bootstrap CSS -->
    <link href="{% static 'store/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap core CSS -->

    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'store/css/style.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'store/css/responsive.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'store/css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    {% block categories %}
    <!-- Start Cart  -->
    <div class="cart-box-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-main table-responsive">
                        <table class="table">
                            <thead>
                                <tr>

                                    <th>Name</th>
                                    <th>Price</th>
                                    <th>Quanity</th>
                                    <th>Subtotal</th>
                                    <th>Delete item</th>
                                </tr>
                            </thead>

                            {% for item in cart %}
                            <tbody>
                                <tr>

                                    <td class="name-pr">
                                        <a href="#">
                                            {{ item.item.name}}
								</a>
                                    </td>
                                    <td class="price-pr">
                                        <p>{{ item.price }}</p>
                                    </td>
                                    <td class="quantity-box">
                                        <form action="{% url 'cart:onchange_add_view' item.item.id %}" method="POST">
                                            {{ item.update_quantity_form.quantity }}
                                            {{ item.update_quantity_form.update_quantity }}
                                            {% csrf_token %}

                                        </form>

                                    </td>
                                    <td class="total-pr">
                                        <p>{{ item.total_cost }} </p>
                                    </td>
                                    <td class="remove-pr">

									<a href="{% url 'cart:cart_remove' item.item.id %}"><i class="fas fa-times"></i>
								</a>
                                    </td>
                                </tr>
                                </tr>
                            </tbody>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>

            <!-- Update Cart  -->
<form action="/cart/">
    <center><button type="submit" class="btn hvr-hover">REFRESH CART</button></center>
</form>
            <div class="row my-5">
                <div class="col-lg-8 col-sm-12"></div>
                <div class="col-lg-4 col-sm-12">
                    <div class="order-box">
                        <h3>Order summary</h3>

                        <hr>
                        <div class="d-flex gr-total">
                            <h5>Sum:</h5>
                            <div class="ml-auto h5"> {{ cart.get_total_price }} $</div>
                        </div>
                        <hr>
                    </div>
                </div>
                <div class="col-12 d-flex shopping-box"><a href="{% url 'orders:checkout' %}" class="ml-auto btn hvr-hover">Checkout</a> </div>
            </div>

        </div>
    </div>
    <!-- End Cart -->

    {% endblock %}

store/templates/store/checkout-completed.html
{% extends "store/base.html" %}
{% load static %}
<!-- Basic -->

{% block categories %}
<br>
<h1>
    <center>Order completed!</center>

</h1>
<center><p>Your order number is: <strong>{{ order.id }}</strong></p></center>
<center><p>In a short while you should recieve a confirmation email.</p></center>
<center><p>Another, <strong>hand crafted</strong> will follow soon, containing details and expected shipping date, and Your PayPal payment details.</p></center>
<br>
<br>
<form action="/">
    <center><button type="submit" class="btn hvr-hover">BACK TO MAIN PAGE</button></center>
</form>
<br>
{% endblock %}

store/templates/store/gallery.html
{% extends "store/base.html" %}
{% load static %}

{% block categories %}
    <!-- Start Gallery  -->
    <div class="products-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1>My projects:</h1>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="special-menu text-center">
                        <div class="button-group filter-button-group">
                            <button class="active" data-filter="*">Wszystko</button>
                            {% for category in categories %}
                                <button data-filter=".{{category.id}}">{{ category }}</button>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="row special-list">
                {% for category in categories %}
                    {% for gallery_item in category.galleryitem_set.all %}
                        {% if gallery_item.active %}
                            <div class="col-lg-3 col-md-6 special-grid {{category.id}}">
                                <div class="products-single fix">
                                    <div class="box-img-hover">
                                        <div class="type-lb">
                                            <p class="sale">{{ category }}</p>
                                        </div>
                                        <img src="{{gallery_item.primary_picture.url }}" class="img-fluid" alt="Image">
                                        <div class="mask-icon">

                                            <a class="cart" href="{{gallery_item.get_absolute_url }}">See more!</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endfor %}


            </div>
        </div>
    </div>



    <!-- End Gallery  -->

{% endblock %}

store/templates/store/thank-you.html
{% extends "store/base.html" %}
{% load static %}

{% block categories %}
    <!-- Start Contact Us  -->
    <div class="contact-box-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <div class="contact-form-right">
                        <center><h2>Thank you! </h2></center>
                        <br>
                        <form action="/">
                            <center><button type="submit" class="btn hvr-hover">BACK TO MAIN PAGE</button></center>
</form>
<br>
                        <br>



                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Cart -->

{% endblock %}